In [2]:
import numpy as np
matrix = np.matrix("1,5,7;2,6,9;4,8,3")
mul = matrix * 2
print("Матрица, умноженная на 2: \n", mul)
mul[mul > 10] = 0
print("Матрица с заменёнными элементами: \n",mul)

Матрица, умноженная на 2: 
 [[ 2 10 14]
 [ 4 12 18]
 [ 8 16  6]]
Матрица с заменёнными элементами: 
 [[ 2 10  0]
 [ 4  0  0]
 [ 8  0  6]]


In [3]:
arr = np.random.randint(1, 101, 20)
print(arr)
div_5 = arr[arr % 5 == 0]
print("Элементы, делящиеся на 5 без остатка:\n", div_5)
arr[arr % 5 == 0] = -1
print("Обновлённый массив:\n", arr)

[17 42 65 62 65 74 77 34 13 74 53 89 63 84 61  5 86 68 24 77]
Элементы, делящиеся на 5 без остатка:
 [65 65  5]
Обновлённый массив:
 [17 42 -1 62 -1 74 77 34 13 74 53 89 63 84 61 -1 86 68 24 77]


In [5]:
a = np.random.randint(0, 51, 5)
print("Первый массив:\n", a)
b = np.random.randint(0, 51, 5)
print("Второй массив:\n", b)
ab = np.vstack((a,b))
print("Объединенный массив:\n", ab)
a1, b1 = np.vsplit(ab, 2)
print("Разделенные массивы: \n Первый:", a1, "\n Второй:", b1)

Первый массив:
 [24 45 35 34 11]
Второй массив:
 [19 11 13  4  4]
Объединенный массив:
 [[24 45 35 34 11]
 [19 11 13  4  4]]
Разделенные массивы: 
 Первый: [[24 45 35 34 11]] 
 Второй: [[19 11 13  4  4]]


In [6]:
a = np.random.randint(-10, 11, 50)
print("Созданный массив: ", a)
summ_all = np.sum(a)
print ("Сумма всех элементов: ", summ_all)
pos_summ = np.sum(a[a > 0])
print("Сумма положительных элементов: ", pos_summ)
neg_summ = np.sum(a[a < 0])
print ("Сумма отрицательных элементов: ", neg_summ)

Созданный массив:  [ -1   2  -5  -9   5 -10  -4  -9  -1  -4   5   6  -1  -4   4   2   7  -9
   6  -6  10   1   9   7  -8   3   0   9  -2   0  10   0  -5  -2  -4  10
  -4   0  -7  -8   8  10   9  -7   6   4  -5   2  -9  -8]
Сумма всех элементов:  3
Сумма положительных элементов:  135
Сумма отрицательных элементов:  -132


In [7]:
edm = np.identity(4)
print("Единичная матрица: \n", edm)
diagm = np.diag([5, 10, 15, 20])
print("Диагональная матрица:\n", diagm)
edm_summ = np.sum(edm)
print("Сумма элементов единичной матрицы: \n", edm_summ)
diagm_summ = np.sum(diagm)
print ("Сумма элементов диагональной матрицы: \n", diagm_summ)
print("По результатам сумма элементов диагональной матрицы оказалась больше, чем единичной.")

Единичная матрица: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Диагональная матрица:
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма элементов единичной матрицы: 
 4.0
Сумма элементов диагональной матрицы: 
 50
По результатам сумма элементов диагональной матрицы оказалась больше, чем единичной.


In [8]:
a = np.random.randint(1, 21, (3, 3))
print("Первая матрица:\n", a)
b = np.random.randint(1, 21, (3, 3))
print("Вторая матрица: \n", b)
summ = a + b
print("CyMMa: ", summ)
razn = a - b
print ("Разница: ", razn)
proz = a * b
print("Произведение: ", proz)

Первая матрица:
 [[ 3 14  6]
 [10 16  4]
 [ 4  8 20]]
Вторая матрица: 
 [[20 12 12]
 [11  8  2]
 [ 5 17 15]]
CyMMa:  [[23 26 18]
 [21 24  6]
 [ 9 25 35]]
Разница:  [[-17   2  -6]
 [ -1   8   2]
 [ -1  -9   5]]
Произведение:  [[ 60 168  72]
 [110 128   8]
 [ 20 136 300]]


In [9]:
a = np.random.randint(1, 11, (2, 3))
print ("Первая матрица:\n", a)
b = np.random.randint(1, 11, (3, 2))
print("Вторая матрица: \n", b)
mult = a @ b
print("Матричное умножение: \n", mult)

Первая матрица:
 [[3 6 7]
 [2 3 6]]
Вторая матрица: 
 [[6 2]
 [5 2]
 [3 6]]
Матричное умножение: 
 [[69 60]
 [45 46]]


In [10]:
a = np.random.randint(1, 21, (3, 3))
print ("Матрица: \n", a)
det = np.linalg.det(a)
print ("Определитель: \n", det)
if np.isclose(det, 0):
    inv = "Матрица вырождена"
else:
    inv = np.linalg.inv(a)
print("Обратная матрица: \n", inv)

Матрица: 
 [[10 15  6]
 [10 16  7]
 [20 18  2]]
Определитель: 
 19.999999999999954
Обратная матрица: 
 [[-4.7   3.9   0.45]
 [ 6.   -5.   -0.5 ]
 [-7.    6.    0.5 ]]


In [11]:
a = np.random.randint(1, 51, (4, 4))
print ("Матрица: \n", a)
transp = a.T
print("Транспонированная матрица:\n", transp)
value = np.trace(a)
print ("След матрицы:\n", value)

Матрица: 
 [[14 30  2 31]
 [ 6  5  5 42]
 [29 32 18  7]
 [ 2  8  1 43]]
Транспонированная матрица:
 [[14  6 29  2]
 [30  5 32  8]
 [ 2  5 18  1]
 [31 42  7 43]]
След матрицы:
 80


In [12]:
A = np.array([[2, 3, -1],
[4, -1, 2],
[-3, 5, 4]])
B = np.array([5, 6, -2])
result = np.linalg.solve(A, B)
print ("Решение системы: ", result)

Решение системы:  [1.63963964 0.57657658 0.00900901]


In [13]:
A = np.array([[2, -1, 0],    # Уравнение 1: 2x - y = 0 - жильё
              [0, -1.3, 1],  # Уравнение 2: -1.3y + z = 0 - питание
              [1, 1, 1]])      # Уравнение 3: x + y + z = 150000 - общий бюджет

# Вектор правых частей
B = np.array([0, 0, 150000])

# Решение методом Крамера
det_A = np.linalg.det(A)

if det_A != 0:
    # Заменяем столбцы по очереди на вектор B
    kram1 = np.linalg.det(np.column_stack([B, A[:, 1], A[:, 2]])) / det_A  # Для x
    kram2 = np.linalg.det(np.column_stack([A[:, 0], B, A[:, 2]])) / det_A  # Для y
    kram3 = np.linalg.det(np.column_stack([A[:, 0], A[:, 1], B])) / det_A  # Для z
    kramer = np.array([kram1, kram2, kram3])
else:
    kramer = "Метод не применим"

# Решение матричным методом
if det_A == 0:
    matrix = "Метод не применим"
else:
    matrix = np.linalg.inv(A).dot(B)  # Умножение обратной матрицы на вектор B

# Решение с помощью встроенной функции NumPy
numpy_solution = np.linalg.solve(A, B)

print("Метод Крамера: ", kramer)
print("Метод матричного уравнения: ", matrix)
print("Библиотека NumPy: ", numpy_solution)

Метод Крамера:  [26785.71428571 53571.42857143 69642.85714286]
Метод матричного уравнения:  [26785.71428571 53571.42857143 69642.85714286]
Библиотека NumPy:  [26785.71428571 53571.42857143 69642.85714286]
